version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "be:7c:52:8a:37:2c:d0:f5:3a:38:ca:ce:16:59:02:d4"
      - run:
          name: install dependencies
          command: |
            apk add --update ansible
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory main-remote.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
