# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1

defaults: &defaults
  docker:
    - image: amazon/aws-cli
# Orchestrate or schedule a set of jobs
jobs:
  # Name the workflow "welcome"
  createinfrastructure:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: creating backend infrastructure
          command: |
            aws cloudformation create-stack \
            --stack-name deploy\
            --template-body template.yml\
            --region=us-west-2 \

workflows:
  my_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - createinfrastructure
