version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e6:ce:54:87:67:b8:3a:63:b0:e9:61:7e:31:a0:80:01"
      - run:
          name: install dependencies
          command: |
            apk add --update ansible
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
